//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../voucher.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;
using System;

/// <summary>
/// This class provides an empty implementation of <see cref="IvoucherListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode ("ANTLR", "4.5.1")]
[System.CLSCompliant (false)]
public partial class voucherBaseListener : IvoucherListener
{
	/// <summary>
	/// Enter a parse tree produced by <see cref="voucherParser.voucher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoucher ([NotNull] voucherParser.VoucherContext context)
	{
	}

	/// <summary>
	/// Exit a parse tree produced by <see cref="voucherParser.voucher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoucher ([NotNull] voucherParser.VoucherContext context)
	{
	}

	/// <summary>
	/// Enter a parse tree produced by <see cref="voucherParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine ([NotNull] voucherParser.LineContext context)
	{
	}

	/// <summary>
	/// Exit a parse tree produced by <see cref="voucherParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine ([NotNull] voucherParser.LineContext context)
	{		
		foreach (var child in context.children) {
			Console.Out.WriteLine (child.GetText ());
		}
	}

	/// <summary>
	/// Enter a parse tree produced by <see cref="voucherParser.price"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrice ([NotNull] voucherParser.PriceContext context)
	{		
	}

	/// <summary>
	/// Exit a parse tree produced by <see cref="voucherParser.price"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrice ([NotNull] voucherParser.PriceContext context)
	{
		Console.Out.WriteLine (context.GetText ());
	}

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule ([NotNull] ParserRuleContext context)
	{
	}

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule ([NotNull] ParserRuleContext context)
	{
	}

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal ([NotNull] ITerminalNode node)
	{
	}

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode ([NotNull] IErrorNode node)
	{
	}
}
