//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../voucher.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class voucherLexer : Lexer {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, NEWLINE=5, INT=6, DECIMALSEPARATOR=7;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "NEWLINE", "INT", "DECIMALSEPARATOR"
	};


	public voucherLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Summe'", "'SUMME'", "'Total'", "'TOTAL'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "NEWLINE", "INT", "DECIMALSEPARATOR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "voucher.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\t\x35\b\x1\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x3"+
		"\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3"+
		"\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x3"+
		"\x5\x3\x6\x6\x6+\n\x6\r\x6\xE\x6,\x3\a\x6\a\x30\n\a\r\a\xE\a\x31\x3\b"+
		"\x3\b\x2\x2\t\x3\x3\x5\x4\a\x5\t\x6\v\a\r\b\xF\t\x3\x2\x5\x4\x2\f\f\xF"+
		"\xF\x3\x2\x32;\x5\x2))..\x30\x30\x36\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2\x2"+
		"\x2\x2\a\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2\x2\r\x3\x2\x2\x2"+
		"\x2\xF\x3\x2\x2\x2\x3\x11\x3\x2\x2\x2\x5\x17\x3\x2\x2\x2\a\x1D\x3\x2\x2"+
		"\x2\t#\x3\x2\x2\x2\v*\x3\x2\x2\x2\r/\x3\x2\x2\x2\xF\x33\x3\x2\x2\x2\x11"+
		"\x12\aU\x2\x2\x12\x13\aw\x2\x2\x13\x14\ao\x2\x2\x14\x15\ao\x2\x2\x15\x16"+
		"\ag\x2\x2\x16\x4\x3\x2\x2\x2\x17\x18\aU\x2\x2\x18\x19\aW\x2\x2\x19\x1A"+
		"\aO\x2\x2\x1A\x1B\aO\x2\x2\x1B\x1C\aG\x2\x2\x1C\x6\x3\x2\x2\x2\x1D\x1E"+
		"\aV\x2\x2\x1E\x1F\aq\x2\x2\x1F \av\x2\x2 !\a\x63\x2\x2!\"\an\x2\x2\"\b"+
		"\x3\x2\x2\x2#$\aV\x2\x2$%\aQ\x2\x2%&\aV\x2\x2&\'\a\x43\x2\x2\'(\aN\x2"+
		"\x2(\n\x3\x2\x2\x2)+\t\x2\x2\x2*)\x3\x2\x2\x2+,\x3\x2\x2\x2,*\x3\x2\x2"+
		"\x2,-\x3\x2\x2\x2-\f\x3\x2\x2\x2.\x30\t\x3\x2\x2/.\x3\x2\x2\x2\x30\x31"+
		"\x3\x2\x2\x2\x31/\x3\x2\x2\x2\x31\x32\x3\x2\x2\x2\x32\xE\x3\x2\x2\x2\x33"+
		"\x34\t\x4\x2\x2\x34\x10\x3\x2\x2\x2\x5\x2,\x31\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
